=== oguzdemir95/BTK_Akademi/DokumanTipleriveVeriFormatlari/dtd_sema.dtd
<!ELEMENT ogrenciler (ogrenci+)>
    <!ELEMENT ogrenci (isim,numara,okul)>
    <!ELEMENT isim (#PCDATA)>
    <!ELEMENT numara (#PCDATA)>
    <!ELEMENT okul (#PCDATA)>

    <!ATTLIST ogrenci 
        id CDATA #REQUIRED 
        sinif (1|2|3|4) #IMPLIED
    >

    <!ENTITY okul1 SYSTEM "Mustafa Kemal Atatürk İlkokulu">
    <!ENTITY okul2 SYSTEM "Mehmet Akif Ersoy İlkokulu">

=== oguzdemir95/BTK_Akademi/DokumanTipleriveVeriFormatlari/dtd_ornek.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ogrenciler SYSTEM "dtd_sema.dtd">

<ogrenciler>
    <ogrenci id="1" sinif="1">
        <isim>Orhan</isim>
        <numara>78</numara>
        <okul>&okul1;</okul>
    </ogrenci>

    <ogrenci id="2">
        <isim>Selim</isim>
        <numara>85</numara>
        <okul>&okul2;</okul>
    </ogrenci>
</ogrenciler>
