=== oguzdemir95/BTK_Akademi/DokumanTipleriveVeriFormatlari/xsd_sema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- Root Element -->
    <xs:element name="ogrenciler">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ogrenci" minOccurs="1" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Child Element -->
     <xs:element name="ogrenci">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="isim" type="xs:string"></xs:element>
                <xs:element name="numara" type="xs:integer"></xs:element>
                <xs:element name="okul" type="xs:string"></xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:integer" use="required"></xs:attribute>
            <xs:attribute name="sinif">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:enumeration value="1"/>
                        <xs:enumeration value="2"/>
                        <xs:enumeration value="3"/>
                        <xs:enumeration value="4"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
     </xs:element>
</xs:schema>

=== oguzdemir95/BTK_Akademi/DokumanTipleriveVeriFormatlari/xsd_ornek.xml
<?xml version="1.0" encoding="UTF-8"?>


<ogrenciler xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="xsd_sema.xsd">
    <ogrenci id="1" sinif="1">
        <isim>Orhan</isim>
        <numara>78</numara>
        <okul>Mustafa Kemal Atatürk İlkokulu</okul>
    </ogrenci>

    <ogrenci id="2">
        <isim>Selim</isim>
        <numara>85</numara>
        <okul>Mehmet Akif Ersoy İlkokulu</okul>
    </ogrenci>
</ogrenciler>
